apiVersion: v1
kind: Namespace
metadata:
  name: from-jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-deployment
  labels:
    app: wiremock
  namespace: from-jenkins
spec:
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      containers:
      - name: wiremock-yc
        image: mapp-registry.corp.mvideo.ru:5000/wiremock_yc:latest
        ports:
        - containerPort: 8080
